CREATE TABLE IF NOT EXISTS complaint_moderators (
    id SERIAL PRIMARY KEY,
    steam_id VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    can_reply BOOLEAN NOT NULL DEFAULT TRUE,
    can_close BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);