ALTER TABLE complaints ADD COLUMN IF NOT EXISTS closed_by_steam_id VARCHAR(50) NULL;
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS rating INTEGER NULL;
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS rating_comment TEXT NULL;
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS rated_at TIMESTAMP NULL;