ALTER TABLE poll_votes ADD COLUMN IF NOT EXISTS voter_name TEXT DEFAULT '';
ALTER TABLE poll_votes ADD COLUMN IF NOT EXISTS voter_avatar TEXT DEFAULT '';
ALTER TABLE poll_votes ADD COLUMN IF NOT EXISTS voter_steam_id TEXT DEFAULT '';